#!/usr/bin/env python3
import sys
import os
import errno
import subprocess
import traceback
import time
import json
import argparse

from client import RancherClient
from client import RancherConfig

class RancherAdjust:
    VERSION="0.1"

    def __init__(self, *args, **kwargs):
        self.config = RancherConfig()
        self.client = RancherClient(self.config)

        self.parser = argparse.ArgumentParser(description='Adjust Rancher Stack Settings')
        self.parser.add_argument('stackname', nargs='?', help='Name of the stack to update. Pass a capability.json file to update that stack.', default=None)
        self.parser.add_argument('--version', help='Print the current version', action='store_true')
        self.parser.add_argument('--info', help='Print version and capabilities in JSON.', action='store_true')
        self.parser.add_argument('--describe', nargs='?', help='Describe actions which can be performed on a stack.', action='append')

        self.args = self.parser.parse_args()

    def describe(self, stack_id):
        try:
            r = self.client.describe(stack_id)
        except (Exception) as e:
            traceback.print_exc(file=sys.stderr)
            print(json.dumps({"error":e.__class__.__name__, "class":"failure", "message":str(e)}))
            sys.exit(3)

        self.client.print(r)

    def adjust(self, stackname):
        data = json.load(sys.stdin)
        data = data.get('rancher', {}).get('services', {})
        try:
            for servicename in data.keys():
                try:
                    self.client.services(stack_name=stackname, name=servicename, action='upgrade', body=data[servicename])
                except PermissionError as e:
                    print(json.dumps({"error":e.__class__.__name__, "class":"failure", "message":str(e)}))
        except Exception as e:
            traceback.print_exc(file=sys.stderr)
            print(json.dumps({"error":e.__class__.__name__, "class":"failure", "message":str(e)}))
            sys.exit(3)

    def run(self):
        if self.args.version:
            print(self.VERSION)
        elif self.args.info:
            print(json.dumps({"version":self.VERSION, "has_cancel":True}))
        elif self.args.describe:
            self.describe(self.args.describe[0])
        elif self.args.stackname:
            self.adjust(self.args.stackname)
        else:
            self.parser.print_help()

if __name__ == "__main__":
    adjuster = RancherAdjust()
    adjuster.run()
